apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "k8s-events-logger.name" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "k8s-events-logger.name" . }}
data:
  dump-events.sh:|-
    #!/usr/bin/env sh
    kubectl get events --all-namespaces --watch \
        {{.lastTimestamp}} {{.type}} {{.involvedObject.namespace}}:{{.involvedObject.name}} {{.involvedObject.kind}}  {{.message}} {{.reason}}{{"\n"}}