apiVersion: v1
kind: Deployment
metadata:
  name: {{ template "k8s-events-logger.fullname" . }}
  labels:
    app: {{ template "k8s-events-logger.name" . }}
    chart: {{ template "k8s-events-logger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "k8s-events-logger.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "k8s-events-logger.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh"]
          args: ["dump-events.sh"]
          volumeMounts:
            - name: executable
              mountPath: /dump-events.sh
              subPath: dump-events.sh
      volumes:
        - name: executable
          configMap:
            name: {{ template "k8s-events-logger.fullname" . }}


{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
